# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_customuser_more_relaxed_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(
                choices=[
                    ('en',
                     'English'),
                    ('de',
                     'German')],
                default='en',
                help_text='Preferred language for communications',
                max_length=20,
                verbose_name='preferred language'),
        ),
    ]
