# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_customuser_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(
                default='en',
                help_text='Preferred language (code) for communications',
                max_length=20,
                verbose_name='preferred language'),
        ),
    ]
