# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20170711_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prevent_self_unlock',
            field=models.BooleanField(
                default=False,
                help_text='Explicitly prevent this user to unlock their account using the Unlock Account functionality.',
                verbose_name='prevent self unlock'),
        ),
    ]
