# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_customuser_prevent_self_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='require_2_fact_auth',
            field=models.BooleanField(
                default=False,
                help_text='Requires this user to use two factor authentication to access the system.',
                verbose_name='require two-factor authentication'),
        ),
    ]
