# Generated by Django 2.1.4 on 2018-12-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_customuser_require_2_fact_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinggroup',
            name='registry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rdrf.Registry'),
        ),
    ]
