version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/rdrf/rdrf/frontend"
    schedule:
      interval: "daily"
    # Always increase the version requirement
    # to match the new version. Not just yarn lock!
    versioning-strategy: increase
  - package-ecosystem: "pip"
    directory: "/rdrf"
    schedule:
      interval: "daily"
    versioning-strategy: increase
  
