version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Always increase the version requirement
    # to match the new version. not just yarn lock
    versioning-strategy: increase
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Always increase the version requirement
    # to match the new version. not just yarn lock
    versioning-strategy: increase
  
