#
FROM muccg/angelman-base
MAINTAINER https://bitbucket.org/ccgmurdoch/angelman/

ARG ARG_GIT_TAG=next_release

ENV GIT_TAG $ARG_GIT_TAG
ENV PIP_OPTS="--no-cache-dir"
ENV PIP_INDEX_URL="https://pypi.python.org/simple"
ENV PIP_TRUSTED_HOST="127.0.0.1"

# Project specific deps
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  libpcre3-dev \
  libpq-dev \
  libssl-dev \
  libyaml-dev \
  zlib1g-dev \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN env --unset=DEBIAN_FRONTEND

COPY .version /.version
RUN cat /.version
ADD https://raw.githubusercontent.com/muccg/rdrf/${GIT_TAG}/docker-entrypoint.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh

VOLUME ["/data"]

ENV HOME /data
WORKDIR /data

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["tarball"]
