# 
FROM muccg/rdrf-base
MAINTAINER https://bitbucket.org/ccgmurdoch/angelman/

ARG ARG_GIT_TAG

ENV GIT_TAG $ARG_GIT_TAG

ADD build/rdrf-$GIT_TAG.tar.gz /

EXPOSE 9100 9101
VOLUME ["/data"]

RUN cp docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Drop privileges, set home for ccg-user
USER ccg-user
ENV HOME /data
WORKDIR /data

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["uwsgi"]
