version: '2'
services:

  # note: the host aliases are to alow the prod stack to be used as a test stack

  dbprod:
    extends:
      file: docker-compose-common.yml
      service: db
    networks:
      default:
        aliases:
          - dbtest

  dbclinicalprod:
    extends:
      file: docker-compose-common.yml
      service: db
    networks:
      default:
        aliases:
          - dbclinicaltest
  
  dbreportingprod:
    extends:
      file: docker-compose-common.yml
      service: db
    networks:
      default:
        aliases:
          - dbreportingtest

  rediscacheprod:
    extends:
      file: docker-compose-common.yml
      service: rediscache
    networks:
      default:
        aliases:
          - rediscachetest

  cacheprod:
    extends:
      file: docker-compose-common.yml
      service: cache
    networks:
      default:
        aliases:
          - cachetest

  nginxprod:
    extends:
      file: docker-compose-common.yml
      service: nginx
    depends_on:
      - uwsgiprod
    networks:
      default:
        aliases:
          - nginxtest

  celeryworker:
    extends:
      file: docker-compose-common.yml
      service: celeryworker
    volumes:
      - uwsgi-prod-data:/data
    depends_on:
      - dbprod
      - rediscacheprod

  uwsgiprod:
    image: muccg/rdrf:${BUILD_VERSION}
    command: uwsgi_local
    environment:
      - DEBUG=0
      - WAIT_FOR_DB=1
      - WAIT_FOR_CLINICAL_DB=1
      - WAIT_FOR_REPORTING_DB=1
      - WAIT_FOR_CACHE=1
      - DJANGO_FIXTURES=test
      - ALLOWED_HOSTS=*
      - DEIDENTIFIED_SITE_ID=testing
      - CSRF_TRUSTED_ORIGINS=localhost nginxtest
      - CACHESERVER=cacheprod
      - DBSERVER=dbprod
      - CLINICAL_DBSERVER=dbclinicalprod
      - REPORTING_DBSERVER=dbreportingprod
      - CACHE_DISABLED=1
    volumes:
        - uwsgi-prod-data:/data
    depends_on:
      - dbprod
      - dbclinicalprod
      - dbreportingprod
      - cacheprod
    ports:
      - "9000:9000"
    networks:
      default:
        aliases:
          - uwsgitest
          - uwsgi

  runservertest:
    extends:
      file: docker-compose-common.yml
      service: runserver
    volumes_from:
      - datatest
    command: runserver
    environment:
      - DJANGO_FIXTURES=test
      - ALLOWED_HOSTS=*
      - CACHESERVER=cachetest
      - DBSERVER=dbtest
      - CLINICAL_DBSERVER=dbclinicaltest
      - REPORTING_DBSERVER=dbreportingtest
      - DESIGN_MODE=1
      - CACHE_DISABLED=1
    depends_on:
      - dbtest
      - dbclinicaltest
      - dbreportingtest
      - cachetest
    ports:
      - "18000:8000"


volumes:
  uwsgi-prod-data:
