# Container used to build bpaotu
FROM node:9.11.1
MAINTAINER https://github.com/muccg/bpaotu

RUN env | sort

COPY docker-entrypoint-node.sh /app/docker-entrypoint-node.sh

VOLUME ["/data"]

ENV HOME /data
WORKDIR /data

ENTRYPOINT ["/app/docker-entrypoint-node.sh"]
CMD ["build"]
