# Container used to build rdrf frontend
#FROM node:10.16.3
FROM node:18.12.0
MAINTAINER https://github.com/muccg/rdrf

RUN env | sort

COPY docker-entrypoint-node.sh /app/docker-entrypoint-node.sh

VOLUME ["/data"]

ENV YARN_CACHE_FOLDER /frontendbuild/yarn_cache
RUN mkdir -p /frontendbuild/yarn_cache
RUN mkdir -p /frontendbuild/build
RUN chown -R node:node /frontendbuild
ENV HOME /frontendbuild
USER node
WORKDIR /app/rdrf/rdrf/frontend

ENTRYPOINT ["/app/docker-entrypoint-node.sh"]
CMD ["build"]
