# Generated by Django 3.2.15 on 2022-11-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rdrf', '0145_auto_20220914_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualisationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('config', models.JSONField()),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.registry')),
            ],
        ),
    ]
