# Generated by Django 3.2.15 on 2022-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_visualisationconfig_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisationconfig',
            name='title',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visualisationconfig',
            name='code',
            field=models.CharField(choices=[('tofc', 'Types of Forms Completed'), ('pcf', 'Patients Who Completed Forms'), ('fgc', 'FieldGroupComparison')], max_length=80),
        ),
    ]
