# Generated by Django 3.2.15 on 2022-11-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0145_auto_20220914_1523'),
        ('dashboards', '0003_auto_20221114_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualisationBaseDataConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField()),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.registry')),
            ],
        ),
        migrations.AddField(
            model_name='visualisationconfig',
            name='base_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.visualisationbasedataconfig'),
        ),
    ]
