# Generated by Django 3.2.15 on 2022-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_auto_20221114_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisationconfig',
            name='config',
            field=models.JSONField(null=True),
        ),
    ]
