# Generated by Django 3.2.15 on 2022-11-15 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_alter_visualisationconfig_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisationbasedataconfig',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualisationbasedataconfig',
            name='data',
            field=models.JSONField(default={'state': 'initial'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualisationbasedataconfig',
            name='state',
            field=models.CharField(choices=[('E', 'Empty'), ('D', 'Data Loaded')], default='E', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualisationbasedataconfig',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
