# Generated by Django 3.2.15 on 2022-11-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_auto_20221115_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisationconfig',
            name='code',
            field=models.CharField(choices=[('tofc', 'Types of Forms Completed'), ('pcf', 'Patients Who Completed Forms'), ('cfc', 'Combined Field Comparison'), ('cpr', 'Changes in Patient Responses')], max_length=80),
        ),
    ]
