# Generated by Django 3.2.15 on 2022-11-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_alter_visualisationconfig_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisationconfig',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
