# Generated by Django 3.2.15 on 2023-01-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_alter_visualisationconfig_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisationbasedataconfig',
            name='code',
            field=models.CharField(default='basedata', max_length=80),
            preserve_default=False,
        ),
    ]
