# Generated by Django 3.2.15 on 2023-01-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_alter_visualisationconfig_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisationconfig',
            name='code',
            field=models.CharField(choices=[('proms_stats', 'Proms Statistics'), ('cfc', 'Combined Field Comparison'), ('cpr', 'Changes in Patient Responses'), ('sgc', 'Scale Group Comparison'), ('tl', 'Traffic Lights Display')], max_length=80),
        ),
    ]
