#!/bin/bash

# The purpose of this script is to do things with files generated by
# 'create-react-app' after 'build' is run.

echo '1/2 Remove the hash from the generated CSS/JS file'
yarn run build-rename

echo '2/2 Copy build files into'
cp build/static/js/main-bundle.min.js ../static/proms/js/
cp build/static/js/runtime-bundle.min.js ../static/proms/js/
cp build/static/js/vendors-bundle.min.js ../static/proms/js/
cp build/static/css/main.css ../static/proms/css/
cp build/static/css/vendors.css ../static/proms/css/
