#!/bin/bash

# The purpose of this script is to do things with files generated by
# 'create-react-app' after 'build' is run.

echo '1/2 Remove the hash from the generated CSS/JS file'
yarn run build-rename

echo '2/2 Copy build files into'

SRC=/frontendbuild/build/static
DEST=/app/rdrf/rdrf/static/proms

cp $SRC/js/main-bundle.min.js $DEST/js/
cp $SRC/js/runtime-bundle.min.js $DEST/js/
cp $SRC/js/vendors-bundle.min.js $DEST/js/

cp $SRC/css/main.css $DEST/css/
cp $SRC/css/vendors.css $DEST/css/
