# Generated by Django 2.2.24 on 2021-09-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_username', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('umrn', models.CharField(max_length=80)),
                ('token', models.CharField(max_length=80, unique=True)),
                ('external_data_json', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('REC', 'requested'), ('ERR', 'error'), ('APP', 'applied'), ('REC', 'received')], default='REC', max_length=3)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cic_data_json', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HL7Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=20)),
                ('event_map', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
