# Generated by Django 2.2.24 on 2021-09-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intframework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HL7Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=80)),
                ('registry_code', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('state', models.CharField(choices=[('C', 'created'), ('S', 'sent'), ('E', 'error')], default='C', max_length=1)),
                ('error_message', models.TextField()),
            ],
        ),
    ]
