# Generated by Django 2.2.24 on 2021-10-19 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intframework', '0002_hl7message'),
    ]

    operations = [
        migrations.AddField(
            model_name='hl7message',
            name='patient_id',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='HL7MessageFieldUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_field', models.CharField(default='', max_length=200)),
                ('update_status',
                 models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure')], default='Failure',
                                  max_length=10)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('hl7_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates',
                                                  to='intframework.HL7Message')),
            ],
        ),
    ]
