# Generated by Django 2.2.24 on 2021-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intframework', '0003_auto_20211019_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='hl7message',
            name='umrn',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
