# Generated by Django 2.2.24 on 2021-11-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intframework', '0004_hl7message_umrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hl7message',
            name='state',
            field=models.CharField(choices=[('C', 'created'), ('S', 'sent'), ('R', 'received'), ('E', 'error')], default='C', max_length=1),
        ),
    ]
