# Generated by Django 3.2.15 on 2022-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intframework', '0008_auto_20220311_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hl7messageconfig',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
