# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20161013_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPatient',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('patients.patient',),
        ),
    ]
