# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_auto_20170410_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True,
                verbose_name='Patient Type'),
        ),
    ]
