# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-16 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_clinicianother_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicianother',
            name='use_other',
            field=models.BooleanField(
                default=False),
        ),
        migrations.AlterField(
            model_name='clinicianother',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
