# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-17 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_auto_20180116_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicianother',
            name='clinician_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clinicianother',
            name='clinician_hospital',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clinicianother',
            name='clinician_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
