# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-30 13:01
from __future__ import unicode_literals

import db_file_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_patient_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsent',
            name='form',
            field=models.FileField(blank=True, null=True, storage=db_file_storage.storage.DatabaseFileStorage(), upload_to='rdrf.DBFileStorage/data_bytes/filename/mimetype', verbose_name='Consent form'),
        ),
    ]
