# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-13 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.database


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_patient_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsent',
            name='form',
            field=models.FileField(blank=True, null=True, storage=storages.backends.database.DatabaseStorage(), upload_to='consents', verbose_name='Consent form'),
        ),
    ]
