# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import registry.patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_auto_20180815_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsent',
            name='form',
            field=models.FileField(blank=True, null=True, storage=registry.patients.models.PatientConsentStorage(), upload_to=registry.patients.models.consentfile_upload_to, verbose_name='Consent form'),
        ),
    ]
