# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0032_auto_20181127_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicianother',
            name='clinician_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clinicianother',
            name='clinician_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
