# Generated by Django 2.1.15 on 2020-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0035_auto_20200107_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cic_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
