# Generated by Django 2.2.20 on 2021-06-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0038_auto_20210611_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='rdrf_registry',
            field=models.ManyToManyField(help_text='You must select a registry to save a patient.', related_name='patients', to='rdrf.Registry', verbose_name='Rdrf Registry'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='working_groups',
            field=models.ManyToManyField(help_text='You must only select one centre to save a patient.', related_name='my_patients', to='groups.WorkingGroup', verbose_name='Centre'),
        ),
    ]
