# Generated by Django 2.2.24 on 2021-11-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0039_auto_20210615_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['family_name', 'given_names', 'date_of_birth'], 'permissions': (('can_see_full_name', 'Can see Full Name column'), ('can_see_dob', 'Can see Date of Birth column'), ('can_see_working_groups', 'Can see Working Groups column'), ('can_see_umrn', 'Can see UMRN column'), ('can_see_diagnosis_progress', 'Can see Diagnosis Progress column'), ('can_see_diagnosis_currency', 'Can see Diagnosis Currency column'), ('can_see_genetic_data_map', 'Can see Genetic Module column'), ('can_see_data_modules', 'Can see Data Modules column'), ('can_see_code_field', 'Can see Code Field column')), 'verbose_name_plural': 'Patient List'},
        ),
    ]
