# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0035_auto_20161018_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryform',
            name='position',
            field=models.IntegerField(default=-1),
        ),
    ]
