# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 03:11
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0037_cdefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MongoMigrationDummyModel',
        ),
    ]
