# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0037_registryform_position'),
        ('rdrf', '0040_mongo_django'),
    ]

    operations = [
    ]
