# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0041_merge_20161215_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextformgroup',
            name='ordering',
            field=models.CharField(
                choices=[
                    ('C',
                     'Creation Date'),
                    ('N',
                     'Name')],
                default='C',
                max_length=1),
        ),
    ]
