# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0045_remove_old_cdefile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(choices=[('en', 'English')], max_length=2),
        ),
    ]
