# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0047_auto_20170421_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='description',
            field=models.CharField(
                choices=[
                    ('account-locked',
                     'Account Locked'),
                    ('other-clinician',
                     'Other Clinician'),
                    ('new-patient',
                     'New Patient Registered'),
                    ('account-verified',
                     'Account Verified')],
                max_length=100),
        ),
    ]
