# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0048_auto_20170523_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='description',
            field=models.CharField(
                choices=[
                    ('account-locked',
                     'Account Locked'),
                    ('other-clinician',
                     'Other Clinician'),
                    ('new-patient',
                     'New Patient Registered'),
                    ('new-patient-parent',
                     'New Patient Registered (Parent)'),
                    ('account-verified',
                     'Account Verified')],
                max_length=100),
        ),
    ]
