# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0049_auto_20170601_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryform',
            name='applicability_condition',
            field=models.TextField(
                blank=True,
                help_text='E.g. patient.deceased == True',
                null=True),
        ),
    ]
