# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0050_registryform_applicability_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='description',
            field=models.CharField(
                choices=[
                    ('account-locked',
                     'Account Locked'),
                    ('other-clinician',
                     'Other Clinician'),
                    ('new-patient',
                     'New Patient Registered'),
                    ('new-patient-parent',
                     'New Patient Registered (Parent)'),
                    ('account-verified',
                     'Account Verified'),
                    ('reminder',
                     'Reminder')],
                max_length=100),
        ),
    ]
