# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0051_auto_20170802_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate', name='language', field=models.CharField(
                choices=[
                    ('en', 'English'), ('ar', 'Arabic'), ('es', 'Spanish'), ('de', 'German')], max_length=2), ), ]
