# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0052_auto_20170807_1109'),
    ]

    operations = [
        migrations.RenameModel('Modjgo', 'ClinicalData'),
    ]
