# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0053_auto_20170908_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjudication',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='adjudication',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='adjudicationdecision',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='adjudicationdefinition',
            name='registry',
        ),
        migrations.RemoveField(
            model_name='adjudicationrequest',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='adjudicationresponse',
            name='request',
        ),
        migrations.DeleteModel(
            name='Adjudication',
        ),
        migrations.DeleteModel(
            name='AdjudicationDecision',
        ),
        migrations.DeleteModel(
            name='AdjudicationDefinition',
        ),
        migrations.DeleteModel(
            name='AdjudicationRequest',
        ),
        migrations.DeleteModel(
            name='AdjudicationResponse',
        ),
    ]
