# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0054_auto_20170908_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='django_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='django_model',
            field=models.CharField(db_index=True, default='Patient', max_length=80),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='context_id',
            field=models.IntegerField(db_index=True, blank=True, null=True),
        ),

    ]
