# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0057_new_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(
                choices=[
                    ('en',
                     'English'),
                    ('ar',
                     'Arabic'),
                    ('po',
                     'Polish'),
                    ('es',
                     'Spanish'),
                    ('de',
                     'German')],
                max_length=2),
        ),
    ]
