# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0059_auto_20171116_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(
                choices=[
                    ('en',
                     'English'),
                    ('ar',
                     'Arabic'),
                    ('pl',
                     'Polish'),
                    ('es',
                     'Spanish'),
                    ('de',
                     'German'),
                    ('fr',
                     'French'),
                    ('it',
                     'Italian')],
                max_length=2),
        ),
    ]
