# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-17 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0062_consentrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrule',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
