# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0063_consentrule_enabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
