# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0064_delete_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('verified', 'Verified'), ('updated', 'Updated'), ('disputed', 'Disputed'), ('unknown', 'Unknown')], db_index=True, max_length=80)),
                ('patient_id', models.IntegerField(db_index=True)),
                ('context_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('registry_code', models.CharField(max_length=10)),
                ('form_name', models.CharField(max_length=80)),
                ('section_code', models.CharField(max_length=100)),
                ('item', models.IntegerField(null=True)),
                ('cde_code', models.CharField(max_length=30)),
                ('cde_value', models.TextField()),
                ('username', models.CharField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
