# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0065_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_type',
            field=models.CharField(choices=[('verified', 'Verified'), ('corrected', 'Corrected')], db_index=True, max_length=80),
        ),
    ]
