# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0066_auto_20180319_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='orig_value',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
