# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-21 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0068_auto_20180504_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryform',
            name='display_name',
            field=models.CharField(blank=True, help_text='Form Name displayed to users', max_length=200, null=True),
        ),
    ]
