# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0069_registryform_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryform',
            name='name',
            field=models.CharField(help_text='Internal name: Alphanumeric', max_length=80),
        ),
    ]
