# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-21 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0071_auto_20180521_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondataelement',
            name='important',
            field=models.BooleanField(default=False, help_text='Indicate whether the field should be emphasised with a green asterisk'),
        ),
    ]
