# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-30 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0072_commondataelement_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBFileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='FileStorage',
        ),
        migrations.AlterField(
            model_name='cdefile',
            name='item',
            field=models.FileField(max_length=300, upload_to='rdrf.DBFileStorage/data_bytes/filename/mimetype'),
        ),
    ]
