# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-30 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0072_commondataelement_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80)),
                ('cde', models.ForeignKey(on_delete=models.CASCADE, to='rdrf.CommonDataElement')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('registry', models.ForeignKey(on_delete=models.CASCADE, to='rdrf.Registry')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('cde', models.ForeignKey(on_delete=models.CASCADE, to='rdrf.CommonDataElement')),
                ('precondition', models.ForeignKey(null=True, on_delete=models.CASCADE, to='rdrf.Precondition')),
                ('survey', models.ForeignKey(on_delete=models.CASCADE, related_name='survey_questions', to='rdrf.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='precondition',
            name='survey',
            field=models.ForeignKey(on_delete=models.CASCADE, to='rdrf.Survey'),
        ),
    ]
