# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-15 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import rdrf.models.definition.models
import storages.backends.database


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0072_commondataelement_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdefile',
            name='item',
            field=models.FileField(max_length=300, storage=storages.backends.database.DatabaseStorage(), upload_to=rdrf.models.definition.models.file_upload_to),
        ),
    ]
