# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-17 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import rdrf.db.dbstorage
import rdrf.models.definition.models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0073_auto_20180815_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdefile',
            name='item',
            field=models.FileField(max_length=300, storage=rdrf.db.dbstorage.DatabaseStorage(), upload_to=rdrf.models.definition.models.file_upload_to),
        ),
    ]
