# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-31 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0074_auto_20180831_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='registry',
        ),
        migrations.AddField(
            model_name='surveyassignment',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
