# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-06 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0075_auto_20180831_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyassignment',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('started', 'Started'), ('completed', 'Completed')], max_length=20),
        ),
    ]
