# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-09 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0076_auto_20180906_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicate whether an entity is active or not'),
        ),
    ]
