# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rdrf.models.proms.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_patient_date_of_death'),
        ('rdrf', '0076_auto_20180906_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_token', models.CharField(default=rdrf.models.proms.models.generate_token, max_length=80, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=80)),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('received', 'Received')], max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=models.CASCADE, to='patients.Patient')),
                ('registry', models.ForeignKey(on_delete=models.CASCADE, to='rdrf.Registry')),
            ],
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='patient_token',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
