# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0077_auto_20180920_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyrequest',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('requested', 'Requested'), ('received', 'Received')], default='created', max_length=20),
        ),
    ]
