# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0078_auto_20180920_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrequest',
            name='survey_name',
            field=models.CharField(default='bp', max_length=80),
        ),
    ]
