# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0079_surveyrequest_survey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='display_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
