# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-14 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0082_auto_20181106_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrequest',
            name='error_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyrequest',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('requested', 'Requested'), ('received', 'Received'), ('error', 'Error')], default='created', max_length=20),
        ),
    ]
