# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0083_auto_20181114_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrequest',
            name='communication_type',
            field=models.CharField(choices=[('qrcode', 'QRCode'), ('email', 'Email')], default='qrcode', max_length=10),
        ),
    ]
