# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-13 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rdrf.helpers.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rdrf', '0084_surveyrequest_communication_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianSignupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('clinician_email', models.CharField(max_length=80)),
                ('state', models.CharField(choices=[('emailed', 'Emailed'), ('signed-up', 'Signed Up'), ('created', 'Created'), ('error', 'Error'), ('rejected', 'Rejected')], default='created', max_length=80)),
                ('token', models.CharField(default=rdrf.helpers.utils.generate_token, max_length=80, unique=True)),
                ('emailed_date', models.DateTimeField(null=True)),
                ('signup_date', models.DateTimeField(null=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registry', models.ForeignKey(on_delete=models.CASCADE, to='rdrf.Registry')),
            ],
        ),
    ]
