# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_patient_date_of_death'),
        ('rdrf', '0086_cliniciansignuprequest_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniciansignuprequest',
            name='clinician_other',
            field=models.ForeignKey(default=None, on_delete=models.CASCADE, to='patients.ClinicianOther'),
            preserve_default=False,
        ),
    ]
