# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-23 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0089_auto_20181120_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliniciansignuprequest',
            name='speciality',
        ),
    ]
