# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0090_remove_cliniciansignuprequest_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniciansignuprequest',
            name='state',
            field=models.CharField(choices=[('emailed', 'Emailed'), ('signed-up', 'Signed Up'), ('activated', 'Activated'), ('created', 'Created'), ('error', 'Error'), ('rejected', 'Rejected')], default='created', max_length=80),
        ),
    ]
