# Generated by Django 2.1.4 on 2018-12-20 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0092_auto_20181203_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniciansignuprequest',
            name='clinician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commondataelement',
            name='pv_group',
            field=models.ForeignKey(blank=True, help_text='If a range, indicate the Permissible Value Group', null=True, on_delete=django.db.models.deletion.CASCADE, to='rdrf.CDEPermittedValueGroup'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='patient_data_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdrf.Section'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='precondition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rdrf.Precondition'),
        ),
    ]
