# Generated by Django 2.1.5 on 2019-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0093_auto_20181220_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
