# Generated by Django 2.1.5 on 2019-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0094_surveyquestion_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='copyright_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
