# Generated by Django 2.1.5 on 2019-05-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0095_auto_20190206_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondataelement',
            name='abnormality_condition',
            field=models.TextField(blank=True, help_text='Rules triggering a visual notification encouraging the user to process with further investigations', null=True),
        ),
    ]
