# Generated by Django 2.1.7 on 2019-05-31 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0096_commondataelement_abnormality_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='context_form_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rdrf.ContextFormGroup'),
        ),
    ]
