# Generated by Django 2.1.7 on 2019-05-31 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0097_survey_context_form_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rdrf.RegistryForm'),
        ),
    ]
