# Generated by Django 2.1.5 on 2019-03-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rdrf.helpers.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0034_auto_20181220_1457'),
        ('rdrf', '0098_survey_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=rdrf.helpers.utils.generate_token, max_length=80, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True)),
                ('state', models.CharField(default='C', max_length=1)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.RDRFContext')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.ParentGuardian')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientReviewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('has_changed', models.CharField(blank=True, max_length=1, null=True)),
                ('current_status', models.CharField(blank=True, max_length=1, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=1, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('patient_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rdrf.PatientReview')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=80)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rdrf.Registry')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('item_type', models.CharField(choices=[('CF', 'Consent Item'), ('DF', 'Demographics Field'), ('SC', 'Section Monitor'), ('MI', 'Add to Section'), ('MU', 'Update Section'), ('V', 'Verification Section')], max_length=2)),
                ('change_question_code', models.CharField(max_length=80)),
                ('current_status_question_code', models.CharField(max_length=80)),
                ('target_code', models.CharField(max_length=80)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdrf.RegistryForm')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rdrf.Review')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdrf.Section')),
            ],
        ),
        migrations.AddField(
            model_name='patientreviewitem',
            name='review_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.ReviewItem'),
        ),
        migrations.AddField(
            model_name='patientreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.Review'),
        ),
        migrations.AddField(
            model_name='patientreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
