# Generated by Django 2.1.5 on 2019-03-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0099_auto_20190328_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='change_question_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='current_status_question_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='target_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
