# Generated by Django 2.1.5 on 2019-04-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0102_reviewitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='code',
            field=models.CharField(default='dummycode', max_length=80),
            preserve_default=False,
        ),
    ]
