# Generated by Django 2.1.5 on 2019-04-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0103_reviewitem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreviewitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreviewitem',
            name='state',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='patientreview',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
