# Generated by Django 2.1.5 on 2019-04-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0104_auto_20190408_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
