# Generated by Django 2.1.5 on 2019-04-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0105_reviewitem_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='fields',
            field=models.TextField(blank=True),
        ),
    ]
