# Generated by Django 2.1.5 on 2019-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0106_reviewitem_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='target_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
