# Generated by Django 2.1.5 on 2019-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0107_reviewitem_target_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='item_type',
            field=models.CharField(choices=[('CF', 'Consent Item'), ('DF', 'Demographics Field'), ('CA', 'Clinician Access'), ('MT', 'Multi Target'), ('SC', 'Section Monitor'), ('MI', 'Add to Section'), ('MU', 'Update Section'), ('V', 'Verification Section')], max_length=2),
        ),
    ]
