# Generated by Django 2.1.7 on 2019-06-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0108_auto_20190502_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewitem',
            name='change_question_code',
        ),
        migrations.RemoveField(
            model_name='reviewitem',
            name='current_status_question_code',
        ),
    ]
