# Generated by Django 2.1.7 on 2019-06-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0109_auto_20190610_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='appearance_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
