# Generated by Django 2.1.7 on 2019-06-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0110_reviewitem_appearance_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('R', 'Caregiver Review'), ('V', 'Clinician Verification')], default='R', max_length=1),
        ),
    ]
