# Generated by Django 2.1.7 on 2019-06-17 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_auto_20181220_1457'),
        ('rdrf', '0111_review_review_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, max_length=80, null=True)),
                ('section_code', models.CharField(blank=True, max_length=80, null=True)),
                ('cde_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('V', 'Verified'), ('N', 'Not Verified'), ('U', 'Unknown')], max_length=1, null=True)),
                ('username', models.CharField(blank=True, max_length=80, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
                ('patient_review_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rdrf.PatientReviewItem')),
            ],
        ),
    ]
