# Generated by Django 2.1.7 on 2019-07-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0113_auto_20190617_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='cde_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
