# Generated by Django 2.1.7 on 2019-07-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0114_surveyquestion_cde_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='cde_path',
            field=models.CharField(blank=True, help_text='Format: <i>/[form_name]/[section_code]/</i><br/>Example: <i>/BaselineTreatmentForm/BASELINETREATMENT/</i>', max_length=255, null=True),
        ),
    ]
