# Generated by Django 2.1.12 on 2019-11-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0117_clinicaldata_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondataelement',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only used for numeric fields', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commondataelement',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only used for numeric fields', max_digits=12, null=True),
        ),
    ]
