# Generated by Django 2.1.12 on 2019-12-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('rdrf', '0118_auto_20191125_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('action_type', models.CharField(choices=[('PR', 'Patient Report')], max_length=2)),
                ('data', models.TextField(null=True)),
                ('groups_allowed', models.ManyToManyField(blank=True, to='auth.Group')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.Registry')),
            ],
        ),
    ]
