# Generated by Django 2.1.12 on 2019-12-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0119_customaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondataelement',
            name='datatype',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Decimal'), ('alphanumeric', 'Alpha Numeric'), ('date', 'Date'), ('boolean', 'Boolean'), ('range', 'Range (Set of allowed values)'), ('calculated', 'Calculated (Derived data element)'), ('file', 'File')], help_text='Type of field', max_length=50),
        ),
    ]
