# Generated by Django 2.1.15 on 2020-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0121_auto_20200213_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaction',
            name='runtime_spec',
            field=models.TextField(null=True),
        ),
    ]
