# Generated by Django 2.1.15 on 2020-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0122_customaction_runtime_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaction',
            name='runtime_spec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
