# Generated by Django 2.1.15 on 2020-06-11 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0035_auto_20200107_0908'),
        ('rdrf', '0123_auto_20200504_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomActionExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=80, null=True)),
                ('name', models.CharField(max_length=80)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=80, null=True)),
                ('download_filepath', models.CharField(max_length=100)),
                ('downloaded', models.BooleanField(default=False)),
                ('downloaded_time', models.DateTimeField(null=True)),
                ('task_result', models.TextField(blank=True)),
                ('runtime', models.IntegerField(help_text='Runtime in seconds', null=True)),
                ('custom_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rdrf.CustomAction')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.Patient')),
                ('user', models.ForeignKey(help_text='The user who executed the action', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
