# Generated by Django 2.1.15 on 2020-06-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0124_surveyquestion_widget_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='widget_config',
            field=models.TextField(blank=True, help_text='Eg: {"max_label": "High", "min_label": "Low", "box_label": "Height"}', null=True),
        ),
    ]
