# Generated by Django 2.1.15 on 2020-06-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0125_customactionexecution_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customactionexecution',
            name='error_string',
            field=models.TextField(blank=True),
        ),
    ]
