# Generated by Django 2.1.15 on 2020-06-11 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0125_surveyquestion_widget_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='customactionexecution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
