# Generated by Django 2.1.15 on 2020-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0129_auto_20200610_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='widget_config',
            field=models.TextField(blank=True, help_text='Eg: {"widget_name": "slider", "max_label": "High",                                                "min_label": "Low", "box_label": "Height"}', null=True),
        ),
    ]
