# Generated by Django 2.1.15 on 2020-07-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0130_auto_20200626_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaction',
            name='action_type',
            field=models.CharField(choices=[('PR', 'Patient Report'), ('SR', 'Patient Status Report'), ('DE', 'Deidentified Data Extract')], max_length=2),
        ),
    ]
