# Generated by Django 2.1.15 on 2020-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0131_auto_20200720_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='customactionexecution',
            name='custom_action_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
