# Generated by Django 2.1.15 on 2020-07-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0133_auto_20200723_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customactionexecution',
            name='custom_action',
        ),
    ]
