# Generated by Django 2.1.15 on 2020-09-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0135_customaction_include_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryYaml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('registry_version_before', models.CharField(blank=True, max_length=20, null=True)),
                ('registry_version_after', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
