# Generated by Django 2.2.13 on 2020-10-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0136_registryyaml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyrequest',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('requested', 'Requested'), ('received', 'Received'), ('error', 'Error'), ('in process', 'In Process')], default='created', max_length=20),
        ),
    ]
