# Generated by Django 2.2.24 on 2021-10-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0138_survey_client_rep_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicfields',
            name='custom_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
