# Generated by Django 2.2.24 on 2021-11-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0139_demographicfields_custom_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
