# Generated by Django 2.2.24 on 2021-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0140_surveyquestion_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='commondataelement',
            name='widget_config',
            field=models.TextField(blank=True, help_text='example: {"tag":"treating_clinician"}'),
        ),
    ]
