# Generated by Django 2.2.24 on 2022-01-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0141_auto_20211202_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaction',
            name='action_type',
            field=models.CharField(choices=[('PR', 'Patient Report'), ('SR', 'Patient Status Report'), ('DE', 'Deidentified Data Extract'), ('VD', 'Visualisation Download')], max_length=2),
        ),
    ]
