# Generated by Django 2.2.24 on 2022-01-18 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0142_auto_20220112_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customactionexecution',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who executed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
