# Generated by Django 2.2.28 on 2022-07-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0143_auto_20220118_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaction',
            name='action_type',
            field=models.CharField(choices=[('PR', 'Patient Report'), ('SR', 'Patient Status Report'), ('DE', 'Deidentified Data Extract'), ('RD', 'Research Download'), ('VD', 'Visualisation Download')], max_length=2),
        ),
    ]
