# Generated by Django 3.2.15 on 2022-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0144_auto_20220711_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicfields',
            name='field',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='demographicfields',
            name='hidden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicfields',
            name='readonly',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
