# Generated by Django 3.2.15 on 2023-02-13 12:46

from django.db import migrations, models
import rdrf.forms.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0145_auto_20220914_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDEValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', rdrf.forms.fields.jsonb.DataField(default=dict)),
            ],
        ),
    ]
