# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_patient_date_of_death'),
        ('rdrf', '0076_auto_20180906_0947'),
        ('explorer', '0005_query_max_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('display_value', models.TextField(blank=True, default='', null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cde', models.ForeignKey(on_delete=models.CASCADE, to='rdrf.CommonDataElement')),
                ('context', models.ForeignKey(on_delete=models.CASCADE, to='rdrf.RDRFContext')),
                ('form', models.ForeignKey(on_delete=models.CASCADE, to='rdrf.RegistryForm')),
                ('patient', models.ForeignKey(on_delete=models.CASCADE, to='patients.Patient')),
                ('registry', models.ForeignKey(on_delete=models.CASCADE, to='rdrf.Registry')),
                ('section', models.ForeignKey(on_delete=models.CASCADE, to='rdrf.Section')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together=set([('registry', 'patient', 'context', 'form', 'section', 'index', 'cde')]),
        ),
    ]
