# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-05 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_auto_20181004_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalue',
            name='column_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
