# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0007_fieldvalue_column_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalue',
            name='datatype',
            field=models.CharField(default='string', max_length=80),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='is_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='raw_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='raw_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
