# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-11 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0009_fieldvalue_raw_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalue',
            name='raw_boolean',
            field=models.NullBooleanField(),
        ),
    ]
