# Generated by Django 3.2.15 on 2022-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0010_fieldvalue_raw_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='raw_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
