#!/usr/bin/env python
#encoding='utf-8'
import sys
import polib
sys.stdout = open(1, 'w', encoding='utf-8', closefd=False)

PREAMBLE = """# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\\n"
"Report-Msgid-Bugs-To: \\n"
"POT-Creation-Date: 2017-04-11 10:57+0800i\\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"
"Language-Team: LANGUAGE <LL@li.org>\\n"
"Language: \\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 \\n"
"&& n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;\\n"
"""

def has_no_translation(entry):
    return not entry.msgstr

def python_formatted(s):
    # e.g. the msgid below is python formatted
    # #: rdrf/rdrf/rdrf/form_view.py:1671
    #, python-format
    #msgid ""
    #"Could not find adjudication for definition %(adj_def)s patient "
    #"%(patient_id)s requested by %(requesting_user)s"
    #msgstr ""
    return "%(" in s


def bad_format(s):
    return "%s" in s


def bad_newline(entry):
    return entry.msgid.startswith("\n") and not entry.msgstr.startswith("\n")

po_files = sys.argv[1:]
untranslated = []
translated = {}

for po_file in po_files:
    entries = polib.pofile(po_file)
    for entry in entries:
        if bad_format(entry.msgid) or bad_format(entry.msgstr):
            continue
        if has_no_translation(entry):
            untranslated.append(entry)
        else:
            if entry.msgid not in translated:
                # in later translations are discarded?
                translated[entry.msgid] = entry

# pump out entries

print(PREAMBLE,sep="")

printed  = []


for msgid in translated:
    entry = translated[msgid]
    # two cases below cause compilation errors
    if entry.msgid.startswith("\n") and not entry.msgstr.startswith("\n"):
        entry.msgstr = "\n" + entry.msgstr

    if python_formatted(entry.msgid) and not python_formatted(entry.msgstr):
        entry.msgstr = "TRANSLATE " + entry.msgstr

    print(entry)

    printed.append(entry.msgid)

# dummy translation replacement number - this allows the admin interface to display all
# the admin pages as it used the translated name as a key in a dictionary
n = 1

for entry in untranslated:
    if entry.msgid in printed:
        continue
    if entry.msgid not in translated:
        if bad_newline(entry):
            if python_formatted(entry.msgid):
                entry.msgstr = "\nTRANSLATE " + entry.msgid[1:]

            else:
                entry.msgstr = "\nTRANSLATE %s" % n
                n += 1

        else:
            if python_formatted(entry.msgid):
                entry.msgstr = "TRANSLATE " + entry.msgid
            else:
                entry.msgstr = "TRANSLATE %s" % n
                n += 1

        
        print(entry)
        printed.append(entry.msgid)

