import logging
from django.contrib.auth.models import Permission


logger = logging.getLogger(__name__)


def add_permissions_to_group(group, role):
    permissions = []
    for permission_code in PERMISSIONS_BY_ROLES[role]:
        try:
            permissions.append(Permission.objects.get(codename=permission_code))
        except Permission.DoesNotExist:
            logger.warning('Permission "%s" required by role "%s" does NOT exist',
                           permission_code, role)
    group.permissions.add(*permissions)


# Note: Permissions have been created initially by copying permissions
# from OPHG staging installation
PERMISSIONS_BY_ROLES = {
    # Not sure if we need this
    # 'AdminOnly': [],
    'Clinical Staff': [
        'add_laboratory',
        'change_laboratory',
        'change_addresstype',
        'delete_addresstype',
        'add_nextofkinrelationship',
        'change_nextofkinrelationship',
        'delete_nextofkinrelationship',
        'add_patient',
        'can_see_data_modules',
        'can_see_diagnosis_currency',
        'can_see_diagnosis_progress',
        'can_see_dob',
        'can_see_full_name',
        'can_see_working_groups',
        'change_patient',
        'delete_patient',
        'add_patientaddress',
        'change_patientaddress',
        'delete_patientaddress',
        'add_patientconsent',
        'change_patientconsent',
        'delete_patientconsent',
        'add_patientrelative',
        'change_patientrelative',
        'delete_patientrelative',
        'add_state',
        'change_state',
        'delete_state',
        'change_questionnaireresponse',
        'delete_questionnaireresponse'],

    'Genetic Curator': [
        'add_gene',
        'change_gene',
        'delete_gene',
        'add_laboratory',
        'change_laboratory',
        'delete_laboratory',
        'add_technique',
        'change_technique',
        'delete_technique',
        'add_addresstype',
        'change_addresstype',
        'delete_addresstype',
        'add_consentvalue',
        'change_consentvalue',
        'delete_consentvalue',
        'add_nextofkinrelationship',
        'change_nextofkinrelationship',
        'delete_nextofkinrelationship',
        'add_parentguardian',
        'change_parentguardian',
        'delete_parentguardian',
        'add_patient',
        'can_see_data_modules',
        'can_see_dob',
        'can_see_full_name',
        'can_see_genetic_data_map',
        'can_see_working_groups',
        'change_patient',
        'delete_patient',
        'add_patientaddress',
        'change_patientaddress',
        'delete_patientaddress',
        'add_patientconsent',
        'change_patientconsent',
        'delete_patientconsent',
        'add_patientdoctor',
        'change_patientdoctor',
        'delete_patientdoctor',
        'add_patientrelative',
        'change_patientrelative',
        'delete_patientrelative',
        'add_state',
        'change_state',
        'delete_state'],

    'Genetic Staff': [
        'add_gene',
        'change_gene',
        'add_laboratory',
        'change_laboratory',
        'add_technique',
        'change_technique',
        'add_addresstype',
        'change_addresstype',
        'delete_addresstype',
        'add_nextofkinrelationship',
        'change_nextofkinrelationship',
        'delete_nextofkinrelationship',
        'add_patient',
        'can_see_data_modules',
        'can_see_dob',
        'can_see_full_name',
        'can_see_genetic_data_map',
        'can_see_working_groups',
        'change_patient',
        'delete_patient',
        'add_patientaddress',
        'change_patientaddress',
        'delete_patientaddress',
        'add_patientconsent',
        'change_patientconsent',
        'delete_patientconsent',
        'add_patientrelative',
        'change_patientrelative',
        'delete_patientrelative',
        'add_state',
        'change_state',
        'delete_state'],

    'Parents': [],
    'Patients': [],

    'Working Group Curators': [
        'add_gene',
        'change_gene',
        'delete_gene',
        'add_laboratory',
        'change_laboratory',
        'delete_laboratory',
        'add_technique',
        'change_technique',
        'delete_technique',
        'add_addresstype',
        'change_addresstype',
        'delete_addresstype',
        'add_doctor',
        'change_doctor',
        'delete_doctor',
        'add_nextofkinrelationship',
        'change_nextofkinrelationship',
        'delete_nextofkinrelationship',
        'add_patient',
        'can_see_data_modules',
        'can_see_dob',
        'can_see_full_name',
        'can_see_working_groups',
        'change_patient',
        'delete_patient',
        'add_patientaddress',
        'change_patientaddress',
        'delete_patientaddress',
        'add_patientconsent',
        'change_patientconsent',
        'delete_patientconsent',
        'add_patientdoctor',
        'change_patientdoctor',
        'delete_patientdoctor',
        'add_patientrelative',
        'change_patientrelative',
        'delete_patientrelative',
        'add_state',
        'change_state',
        'delete_state',
        'change_questionnaireresponse',
        'delete_questionnaireresponse'],

    'Working Group Staff': [
        'add_laboratory',
        'change_laboratory',
        'add_addresstype',
        'change_addresstype',
        'delete_addresstype',
        'add_consentvalue',
        'change_consentvalue',
        'delete_consentvalue',
        'add_nextofkinrelationship',
        'change_nextofkinrelationship',
        'delete_nextofkinrelationship',
        'add_parentguardian',
        'change_parentguardian',
        'delete_parentguardian',
        'add_patient',
        'can_see_data_modules',
        'can_see_diagnosis_currency',
        'can_see_diagnosis_progress',
        'can_see_dob',
        'can_see_full_name',
        'can_see_working_groups',
        'change_patient',
        'delete_patient',
        'add_patientaddress',
        'change_patientaddress',
        'delete_patientaddress',
        'add_patientconsent',
        'change_patientconsent',
        'delete_patientconsent',
        'add_patientrelative',
        'change_patientrelative',
        'delete_patientrelative',
        'add_state',
        'change_state',
        'delete_state']
}
